export enum CaseElementType {
  LOCATION = 'LOCATION',
  CHARACTER = 'CHARACTER',
  EVIDENCE = 'EVIDENCE',
  DOCUMENT = 'DOCUMENT',
  TESTIMONY = 'TESTIMONY',
  QUESTION = 'QUESTION',
  DEDUCTION = 'DEDUCTION',
  BOARD_RELATION = 'BOARD_RELATION',
}
